mantisbt:
  image: vimagick/mantisbt:latest
  ports:
    - "8989:80"
  links:
    - mariadb
  environment:
    - MYSQL_HOST=mariadb
  restart: always
  volumes:
    - ./config_inc_addon.php:/var/www/html/config/config_inc.php

mariadb:
  image: 'docker.io/bitnami/mariadb:10.3-debian-10'
  environment:
    - ALLOW_EMPTY_PASSWORD=yes
    - MARIADB_USER=mantis
    - MARIADB_DATABASE=bugtracker
    - MARIADB_PASSWORD=mantis
    - MARIA_ROOT_PASSWORD=root
  volumes:
      - 'mariadb_data:/bitnami/mariadb'
